### ISSUE TITLE
"Internal Server Error" when opening "My Favorite"

### ISSUE THREAD

**Issue by HunterNan723** [lordfriend/Deneb#146]
My username is HunterNan.
I can favorite bangumi, but they won't show up in my favorites. The server responded with a status of 500. Everything else works fine.

**Comment by lordfriend** [comment]
I've found that error report from Sentry. I'll see it at once.

**Comment by lordfriend** [comment]
This issues is related with Albireo.
for details. see.
 https://github.com/lordfriend/Albireo/issues/135

A new [version](https://github.com/lordfriend/Albireo/pull/137) has been released , which aimed to resolve this issue.
