### ISSUE TITLE
Unable to watch on Chrome

### ISSUE THREAD

**Issue by bgli100** [lordfriend/Deneb#183]
Chrome 80
Can see 307 entry of video file, but the redirected request shows "pending" forever.

Can confirm Edge and iOS Safari works fine in the same network condition

**Comment by lordfriend** [comment]
Hi, Could you provide the id of episode and bangumi?

**Comment by bgli100** [comment]
Every bangumi and every episode.

**Comment by lordfriend** [comment]
So, Do you have some proxy addon in Chrome? HTTP 307 is some private service function. has nothing to do with browsers. the redirected location is based on IP, so If you have a proxy setting try to change that or put the domain into a blacklist.

**Comment by bgli100** [comment]
Proxy addon was configured as "direct" in my Chrome. Just tried turn it off on Chrome addon conf page, still do not work.

**Comment by bgli100** [comment]
The 307 redirect behavior exists on both Edge and Chrome (which I believe is given by server), but Chrome does not process request of the redirected URL. 

https://developers.google.com/web/tools/chrome-devtools/network/reference#timing-explanation

Guess something in this list happens in Chrome?

**Comment by lordfriend** [comment]
If you can confirm that you can download the video file using any other tools or browsers from the given new URL in the 307 response location header. Then we can rule out the network issue. For Chrome it has a cache lock some times causing issues. but all browsers should able to follow the 307 redirect correctly.
I'm using Chrome 80 too. but for now no issue with that 307 redirect.

If there is a message "waiting for cache" when loading the video. You may try no-cache refresh (Shift+ F5 or Ctrl + Shift + R). Which will also reload service-worker that may solve some issue caused by video player code.

**Comment by bgli100** [comment]
I can use both pre-307 and after-307 URL to download video file, using Chrome, if I do it in a new tab.

None of 3 no-cache refresh methods work (Shift+F5, Ctrl+Shift+R, 'Disable Cache' in Dev Tools and refresh).

Cache actually helps to solve the problem. If I do things in sequence: 
1. Go to an episode page, video not loading
2. Go Dev Tools and see URL, open URL in another tab
3. New tab loads video (adding video to cache)
4. Close new tab, refresh old tab with cache enabled
5. Episode page works! (Seems if Chrome finds video in cache, problem won't happen)
6. Refresh with cache disabled, episode page not working again

**Comment by lordfriend** [comment]
Another user also reported this issue in Chrome 81. though I'm using Chrome 80 and have no issue, I already let the developer of that video redistribution service use 302 with no-cache redirect instead of 307.

Feel free to report if you still have the issue.

**Comment by bgli100** [comment]
Still not working.

Changing from 307 to 302 stopped the 6-step workaround from working. (which makes perfect sense)

**Comment by lordfriend** [comment]
Thank you for feedback. Since I cannot reproduce the bug.  It will take some time to be able to figure out the cause. For now, I can only advise you to use Firefox which from another user report can play the video.

**Comment by UVJkiNTQ** [comment]
Meet  same problem.
Please test under incognito mode to avoid the interuption of extensions.

I disabled Header Editor and now the player works fine.
