### ISSUE TITLE
Playing Process Bar Bug in Phone.

### ISSUE THREAD

**Issue by Catofes** [lordfriend/Deneb#19]
![image](https://cloud.githubusercontent.com/assets/3324513/15985321/b2a4fcea-2fae-11e6-8c79-c59842c99f35.png)

**Comment by lordfriend** [comment]
Did you encounter any stalled issue?

**Comment by Catofes** [comment]
No . But the network problem always popup.

**Comment by lordfriend** [comment]
That's may be the data load stalled (when media download timeout for some time the browser will fire a stalled event), The player application handle the event not properly.
This bug may be the same bug with #16

**Comment by lordfriend** [comment]
the stalled event should be handle properly, when a network bandwidth becomes smaller or latency becomes bigger, a stalled event will fired by user-agent, on this situation,the player will show a loading spinner until the download is resume
