### ISSUE TITLE
Feature Proposal

### ISSUE THREAD

**Issue by lynx-cpp** [lordfriend/Deneb#31]
search bangumi on web via name, year, director, CV, etc.

**Comment by lordfriend** [comment]
These features contains in proposal #12

**Comment by HerringtonDarkholme** [comment]
That will require a full blown search engine. Is that too expensive for amateur project?

**Comment by lordfriend** [comment]
I'll not using a search engine like elastic search, but only using database like operator to make a partially match searching.

it will be like the admin panel search

**Comment by lordfriend** [comment]
Close due to outdated
