### ISSUE TITLE
Screenshot cannot be downloaded on iOS.

### ISSUE THREAD

**Issue by kxxoling** [lordfriend/Deneb#39]
![img_4276](https://cloud.githubusercontent.com/assets/1227139/23091406/2099d3f8-f5f0-11e6-9057-acf506c5cc13.PNG)
System: iOS 10.2.1
Browser: Safari
Device: iPad mini 4

**Comment by lordfriend** [comment]
This is not a bug, because Safari (Both iOS and Desktop) does not support a `download ` attribute in `<a>` tag. so I create this polyfill solution to capture the video frame to a canvas and user need to save the canvas manually

**Comment by lordfriend** [comment]
Currently capture is disabled on all mobile device.
