### ISSUE TITLE
Fullscreen mode not work on iOS.

### ISSUE THREAD

**Issue by kxxoling** [lordfriend/Deneb#40]
Episode video fullscreen button not works on iOS.

**Comment by kxxoling** [comment]
Both `webkitRequestFullScreen` and `webkitEnterFullScreen` work on Chrome 56, only  `webkitRequestFullScreen` is used in the code. I didn't figure out the difference between them.

https://github.com/lordfriend/Deneb/blob/8d7587e92e0da19339f873191191c04949bc6a3a/src/app/home/player/player.component.ts#L369

**Comment by lordfriend** [comment]
resolved in new video player
