### ISSUE TITLE
Need gesture controls supported on iOS.

### ISSUE THREAD

**Issue by kxxoling** [lordfriend/Deneb#41]
Gesture control supplies better UX on mobile devices.

This is a suggested product enhancement.

**Comment by lordfriend** [comment]
You suggestion is considerable. currently a player optimization is on the schedule. the whole interactive of player will be redesign and implemented.

**Comment by lordfriend** [comment]
This project is succeed by https://github.com/irohalab/mira-ui, and will be archived.
