### ISSUE TITLE
Needs better starring experience.

### ISSUE THREAD

**Issue by kxxoling** [lordfriend/Deneb#64]
When every season begins I will starring several animes or TV play at once. As the list doesn't support ``open in new tab`` or memorizing scroll position, I have to click to details of 1st bangumi, then back and scroll deeply to the next, then back and scroll deeper...

I have different enhancement suggestions, which have no conflict with each other:

1. Set ``href`` for every bangumi in the bangumi list, so I can use the browser's ``open in new tab`` function.
2. Memorizing scroll position when route changes. It wouldn't break my browsing experience when jumping in different pages.
3. Add the starring component to bangumi list, so I don't need to click into the details page any more.

**Comment by lordfriend** [comment]
solved in #86 

1. bangumi now is a anchor element which has an href to its location
2. scroll position is preserved even user leave current page. Click the top bar to fast return to top.
3. Not implement.
